'use strict';

//selecting an element
// console.log(document.querySelector('.message').textContent); //we need to have class names of the elements we want to manipulate.

//DOM And DOM Manipulation
//Document Object Model(allows js to access HTML elements and styles to manipulate them.)Tree structure generated by browser on HTML load, each element is an object in this tree structure.
//DOM is not a part of JS rather part of WEB APIs(Libraries written in JS, automatically availabe), JS is just a dialect which  can interact with these WEB APIs.

//Setting new Message or Values.
// document.querySelector('.message').textContent = '🎉 Correct Number!';
// document.querySelector('.number').textContent = 13;
// document.querySelector('.score').textContent = 20;

//To set or get the value of an input field.
// document.querySelector('.guess').value = 23;
// console.log(document.querySelector('.guess').value);

//Handling CLick Events.
// 'addEventListener' is a special type of function because it accepts an eventHandlerFunction as its second argument, we can do that beacuse at the end a function is just a value.
// document.querySelector('.check').addEventListener('click', function () {
//   console.log(document.querySelector('.guess').value);//takes input from the input field once the button is cliked and loggs it on the console.
//   // js engine calls this function on its own, as soon as the event happens not when the script ends.
//   document.querySelector('.message').textContent='🎉 Correct Number!'
// });

// Going Further...
let secretNumber = Math.trunc(Math.random() * 20) + 1; //generating a random number btw (1&20).
let score = 20;
let highScore = 0;

const displayMessage = function (message) {
  document.querySelector('.message').textContent = message;
}; //made this fn for refracting the code...we can create many such versions for different tasks happening in this project.

document.querySelector('.check').addEventListener('click', function () {
  const guess = Number(document.querySelector('.guess').value);
  console.log(guess); //as values taken from user are always string type so we need to convert it.

  //When there is no input.
  if (!guess) {
    //nothing in input means 0 which is a falsy value so in order to make this if block run we have to make it true, that's why we used negation...
    // document.querySelector('.message').textContent = '⛔ No number Entered!';
    displayMessage('⛔ No number Entered!');

    //When the player wins.
  } else if (guess === secretNumber) {
    // document.querySelector('.message').textContent = ' 🎉Correct Answer';
    displayMessage('🎉Correct Answer');
    document.querySelector('.number').textContent = secretNumber;

    document.querySelector('body').style.backgroundColor = '#60b347';
    document.querySelector('.number').style.width = '30rem';

    if (score > highScore) {
      highScore = score;
      document.querySelector('.highscore').textContent = highScore;
    }
    //Guess is wrong..(refracted Version)
  } else if (guess !== secretNumber) {
    if (score > 1) {
      document.querySelector('.message').textContent =
        guess > secretNumber ? '📈 Too High' : '📉 Too Low';
      score--;
      document.querySelector('.score').textContent = score;
    } else {
      // document.querySelector('.message').textContent = '💥 You Lost';
      displayMessage('💥 You Lost');
      document.querySelector('.score').textContent = 0;
    }
  }
  // //When the guess is too high.
  // else if (guess > secretNumber) {
  //   if (score > 1) {
  //     document.querySelector('.message').textContent = '📈 Too High';
  //     score--;
  //     document.querySelector('.score').textContent = score;
  //   } else {
  //     document.querySelector('.message').textContent = '💥 You Lost';
  //     document.querySelector('.score').textContent = 0;
  //   }

  //   //When the guess is too low.
  // } else if (guess < secretNumber) {
  //   if (score > 1) {
  //     document.querySelector('.message').textContent = '📉 Too Low';
  //     score--;
  //     document.querySelector('.score').textContent = score;
  //   } else {
  //     document.querySelector('.message').textContent = '💥 You Lost';
  //     document.querySelector('.score').textContent = 0;
  //   }
  // }
});

//Resetting...
document.querySelector('.again').addEventListener('click', function () {
  score = 20;
  secretNumber = Math.trunc(Math.random() * 20) + 1;
  document.querySelector('body').style.backgroundColor = '#222';
  document.querySelector('.score').textContent = score;
  document.querySelector('.number').textContent = '?';
  document.querySelector('.number').style.width = '15rem';
  // document.querySelector('.message').textContent = 'Start Guessing...';
  displayMessage('Start Guessing...');
  document.querySelector('.guess').value = '';
});
